### ISSUE TITLE
Shard Sequence Number recovery

### ISSUE THREAD

**Issue by raakella1** [eBay/HomeObject#102]
During recovery, the shard sequence number is reset to 0. We need to persist the number in metablk and recover on restart
Improve unit tests

**Comment by zichanglai** [comment]
do we really has this issue? when shard is recovered from metalk, pg shard sequence num will be updated in here: https://github.com/eBay/HomeObject/blob/3bf233a1cb0d5bb475ca78700f1f4c75056abb23/src/lib/homestore_backend/hs_shard_manager.cpp#L219

**Comment by zichanglai** [comment]
I enhanced the shard recover unit test to cover this: https://github.com/eBay/HomeObject/pull/114. And from the unit test, we knew PG shard_sequence_num can be recovered after restarted.
