### ISSUE TITLE
Error condition document write up and review

### ISSUE THREAD

**Issue by yamingk** [eBay/HomeObject#124]
Owner: Xiaoxi, Yaming.

Scope:
List all error conditions that HomeObj and HomeStore (including Replicatoin) and review with team and corresponding stake holders. 

Outcome:
1. identify and finalize error conditions and reasonable solutions both in-house and in production.
2. file corresponding issues&tickets to cover and verifiy error condition expected behavior.

**Comment by xiaoxichen** [comment]
https://docs.google.com/document/d/1PFMw-YTxNv8S-p_QPY1Fp7hQwVQkP7VNADgIrN7ZyKY/edit#heading=h.7ic2bl37xu9w

closing this
